---
apiVersion: meta.pkg.crossplane.io/v1
kind: Configuration
metadata:
  name: donothing
spec:
  crossplane:
    version: ">=v1.0.0"
  dependsOn: []
  package: PACKAGE_NAME
  packagePullPolicy: IfNotPresent
  revisionActivationPolicy: Automatic
  revisionHistoryLimit: 3
...
